# -*- coding: utf-8 -*-
"""Checkout Session 类型检测的独立运行时配置。"""

from config.env_loader import apply_env_overrides


# 自动检测默认关闭。proxy 模式不使用 PROXY_POOL，必须显式填写专用代理。
CHECKOUT_SESSION_AUTO_CHECK = False
CHECKOUT_SESSION_PROXY_MODE = "proxy"
CHECKOUT_SESSION_PROXY = ""
CHECKOUT_SESSION_BILLING_COUNTRY = ""
CHECKOUT_SESSION_BILLING_CURRENCY = ""
CHECKOUT_SESSION_TIMEOUT = 35.0
CHECKOUT_SESSION_MAX_ATTEMPTS = 2
CHECKOUT_SESSION_RETRY_DELAY = 1.5
CHECKOUT_SESSION_WORKERS = 1
CHECKOUT_SESSION_QUEUE_LIMIT = 100
CHECKOUT_SESSION_MIN_INTERVAL = 0.4
CHECKOUT_SESSION_JITTER = 0.3


apply_env_overrides(globals(), {
    "CHECKOUT_SESSION_AUTO_CHECK": "bool",
    "CHECKOUT_SESSION_PROXY_MODE": "str",
    "CHECKOUT_SESSION_PROXY": "str",
    "CHECKOUT_SESSION_BILLING_COUNTRY": "str",
    "CHECKOUT_SESSION_BILLING_CURRENCY": "str",
    "CHECKOUT_SESSION_TIMEOUT": "float",
    "CHECKOUT_SESSION_MAX_ATTEMPTS": "int",
    "CHECKOUT_SESSION_RETRY_DELAY": "float",
    "CHECKOUT_SESSION_WORKERS": "int",
    "CHECKOUT_SESSION_QUEUE_LIMIT": "int",
    "CHECKOUT_SESSION_MIN_INTERVAL": "float",
    "CHECKOUT_SESSION_JITTER": "float",
})
